items = [
    {
        'name': 'Penee Pasta',
        'description': 'Barilla Penee Pasta 16oz Box',
        'price': 1.99,
        'image': 'img/penee.jpg',
    },
    {
        'name': 'Tomatoes',
        'description': '2Lbs of Tomatoes',
        'price': 3.99,
        'image': 'img/Tomato_je.jpg',
    },
    {
        'name': 'Olive Oil',
        'description': '16.9Fl oz olive oil',
        'price': 10.99,
        'image': 'img/oliveOil.jpeg',
    },
    {
        'name': 'Garlic',
        'description': 'Garlic Bulb Fresh Whole',
        'price': 0.99,
        'image': 'img/garlic.jpeg',
    },
    {
        'name': 'Basil',
        'description': 'Dried Basil Leaves 1oz',
        'price': 2.99,
        'image': 'img/basil.jpeg',
    },
    {
        'name': 'Parmesan Cheese',
        'description': 'Parmesan Grated Cheese 8oz',
        'price': 3.99,
        'image': 'img/parmcheese.jpeg',
    },
    {
        'name': 'Mozzarella Cheese',
        'description': 'Mozzarella Shredded Cheese 8oz',
        'price': 3.99,
        'image': 'img/mozz.jpeg',
    },
    {
        'name': 'Prosciutto',
        'description': ' Traditional Prosciutto 4oz',
        'price': 5.99,
        'image': 'img/Prosciutto.jpeg',
    },
    {
        'name': 'Balsamic Vinegar',
        'description': 'Balsamic Vinegar 8.5Floz',
        'price': 9.99,
        'image': 'img/BalsamicVinegar.jpeg',
    },
    {
        'name': 'Red Wine',
        'description': 'Stella Rosa Red Wine 750ml',
        'price': 9.99,
        'image': 'img/wine.jpeg',
    },
    {
        'name': 'Ricotta Cheese',
        'description': 'Ricotta Cheese 32oz ',
        'price': 5.99,
        'image': 'img/ricotta.jpeg',
    },
    {
        'name': 'Pancetta',
        'description': 'Italian Pancetta 2.5Lbs',
        'price': 59.99,
        'image': 'img/Pancetta.jpeg',
    },
    {
        'name': 'Onions',
        'description': '1 whole onion',
        'price': 0.99,
        'image': 'img/onion.jpeg',
    },
    {
        'name': 'Eggs',
        'description': '1 Dozen white eggs',
        'price': 3.99,
        'image': 'img/eggs.jpeg',
    },
    {
        'name': 'Mushrooms',
        'description': '4 oz pack of mushrooms',
        'price': 3.99,
        'image': 'img/mushrooms.jpeg',
    },
    {
        'name': 'Oregano',
        'description': 'Oregano 5oz',
        'price': 9.99,
        'image': 'img/oregano.jpeg',
    },
    {
        'name': 'Rosemary',
        'description': 'Rosemary 470ml',
        'price': 1.99,
        'image': 'img/rosemary.jpg',
    },
    {
        'name': 'Thyme',
        'description': 'Organic thyme 0.78oz',
        'price': 6.99,
        'image': 'img/thyme.jpg',
    },
    {
        'name': 'Capers',
        'description': 'Capote Capers 32oz',
        'price': 33.99,
        'image': 'img/capers.jpg',
    },
    {
        'name': 'Anchovies',
        'description': 'Anchovies 3.5oz jar',
        'price': 8.99,
        'image': 'img/anchovies.jpg',
    },
]
